export const GET_FUNDS = "GET_FUNDS";
export const GET_FUNDS_SUCCESS = "GET_FUNDS_SUCCESS";
export const GET_BASKETS = "GET_BASKETS";
export const GET_BASKETS_SUCCESS = "GET_BASKETS_SUCCESS";
export const PUT_BASKET = "PUT_BASKET";
export const PUT_BASKET_SUCCESS = "PUT_BASKET_SUCCESS";
export const DELETE_BASKET = "DELETE_BASKET";
export const DELETE_BASKET_SUCCESS = "DELETE_BASKET_SUCCESS";
